### ISSUE TITLE
O fórum caiu?

### ISSUE THREAD

**Issue by youtubeeicarlos** [leomontenegro6/megaman-zx-advent-traducao-ptbr#2]
O que houve com o fórum cara? Nem tive nem tempo de salvar as traduções, se não for mais usar ele doa pra mim que eu cuido

**Comment by leomontenegro6** [comment]
Manutenção temporária, devido a termos sido forçados a atualizar a versão do SimpleMachinesForum (SMF) para a mais recente, do contrário deixaria de funcionar em abril.

A atualização foi terminada ontem. O tema teve de ser trocado, e parte dos avatares foram perdidos. Mas todas as contas de usuário, bem como os fórum topics e posts, estão intactos. Já pode testar e ver se tá normalizado.

Fechando a issue por não ter relação com o projeto em si.
